routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/welcome', function () {
    return view('welcome');
});

//Route::get('/login', 'AuthController@login');
//Route::post('/postlogin', 'AuthController@postlogin');

//Home
Auth::routes();
Route::get('/', 'HomeController@index');
Route::get('/home', 'HomeController@index')->name('home');

//Resources
Route::resources([
    'menu' => 'MenuController',
    'meja' => 'MejaController',
    'pesanan' => 'PesananController',
    'pesanan/{id}/detail' => 'DetailPesananController',
    'transaksi' => 'TransaksiController',
    'laporan' => 'LaporanController',
    'user' => 'UserController'
]);

Route::get('pesanan/{id}/detail/edit/{id}' ,'DetailPesananController@edit');

//Total
Route::get('pesanan/total/{id}', 'PesananController@getTotal');
Route::get('pesanan/json/{id}', 'PesananController@getJson');

app/Menu.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

/**
 * @method static get()
 * @method static create(array $all)
 * @method static findOrFail(Menu $id)
 * @method static find(Menu $id)
 */
class Menu extends Model
{
    protected $table = 'menu';
    protected $fillable = ['nama', 'harga','jenis_menu'];
}

app/Http/Controllers/MenuController.php
<?php

namespace App\Http\Controllers;

use App\Menu;
use Illuminate\Contracts\View\Factory;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Validation\ValidationException;
use Illuminate\View\View;

//use Illuminate\Http\Response;

class MenuController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        $data = Menu::get();
        return view('menu.index',compact('data'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Factory|View
     */
    public function create()
    {
        return view('menu.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param Request $request
     * @return RedirectResponse
     * @throws ValidationException
     */
    public function store(Request $request)
    {
        $this->validate($request,[
            'nama' => 'required',
            'harga' => 'required',
            'jenis_menu' => 'required'
        ]);

        Menu::create($request->all());

        return redirect()->route('menu.index')->with('sukses','Tambah Menu Berhasil!!');
    }

    /**
     * Display the specified resource.
     *
     * @param Menu $menu
     * @return void
     */
    public function show(Menu $menu)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Menu $id
     * @return Factory|View
     */
    public function edit($id)
    {
        $data = Menu::findOrFail($id);
        return view('menu.edit',compact('data'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param Request $request
     * @param Menu $id
     * @return RedirectResponse
     * @throws ValidationException
     */
    public function update(Request $request, $id)
    {
        $this->validate($request,[
            'nama' => 'required',
            'harga' => 'required',
            'jenis_menu' => 'required'
        ]);

        Menu::find($id)->update($request->all());

        return redirect()->route('menu.index')->with('sukses','Ubah Menu Berhasil!!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Menu $id
     * @return RedirectResponse
     */
    public function destroy($id)
    {
        Menu::find($id)->delete();
        return redirect()->route('menu.index')->with('sukses','Hapus Menu Berhasil!!');
    }
}

resources/views/menu/create.blade.php
@extends('layouts.app')
@section('content')

    <form method="post" action="{{ route('menu.store') }}" enctype="multipart/form-data">
        @csrf
        <div class="panel panel-headline">
            <div class="panel-heading">
                <h3 class="panel-title">Tambah Menu</h3>
                <p class="panel-subtitle">Menambahkan menu baru</p>
            </div>
            <div class="panel-body">
                <div class="form-group">
                    <label for="nama" class="">Nama</label>
                    <div class="">
                        <input type="text" id="nama" class="form-control" name="nama"  required>
{{--                        @if ($errors->has('nama'))--}}
{{--                            <span class="help-block">--}}
{{--                                  <strong>{{ $errors->first('nama') }}</strong>--}}
{{--                            </span>--}}
{{--                        @endif--}}
                    </div>
                </div>
                <div class="form-group">
                    <label for="harga" class="">Harga</label>
                    <div class="">
                        <input type="text" id="harga" class="form-control" name="harga"  required>
{{--                        @if ($errors->has('harga'))--}}
{{--                            <span class="help-block">--}}
{{--                                  <strong>{{ $errors->first('harga') }}</strong>--}}
{{--                            </span>--}}
{{--                        @endif--}}
                    </div>
                </div>
                <div class="form-group">
                    <label for="jenis_menu" class="">Jenis Menu</label>
                    <div class="">
                        <select name="jenis_menu" id="" class="form-control">
                            <option value="">-- Pilih Menu --</option>
                            <option value="Makanan">Makanan</option>
                            <option value="Minuman">Minuman</option>
                        </select>
                    </div>
                </div>
                <button type="submit" class="btn btn-primary" id="submit">Submit</button>
                <button type="reset" class="btn btn-danger">Reset</button>
                <a href="{{route('menu.index')}}" class="btn btn-light pull-right">Kembali</a>
            </div>
        </div>
    </form>
@endsection

resources/views/menu/edit.blade.php
@extends('layouts.app')
@section('content')

    <form method="post" action="{{ route('menu.update', $data->id) }}" enctype="multipart/form-data">
        @csrf
        @method('put')
        <div class="panel panel-headline">
            <div class="panel-heading">
                <h3 class="panel-title">Edit Menu {{$data->nama}}</h3>
                <p class="panel-subtitle">Mengubah menu ini</p>
            </div>
            <div class="panel-body">
                <div class="form-group">
                    <label for="nama" class="">Nama</label>
                    <div class="">
                        <input type="text" id="nama" class="form-control" name="nama" value="{{$data->nama}}" required>
                        {{--                        @if ($errors->has('nama'))--}}
                        {{--                            <span class="help-block">--}}
                        {{--                                  <strong>{{ $errors->first('nama') }}</strong>--}}
                        {{--                            </span>--}}
                        {{--                        @endif--}}
                    </div>
                </div>
                <div class="form-group">
                    <label for="harga" class="">Harga</label>
                    <div class="">
                        <input type="text" id="harga" class="form-control" name="harga" value="{{$data->harga}}" required>
                        {{--                        @if ($errors->has('harga'))--}}
                        {{--                            <span class="help-block">--}}
                        {{--                                  <strong>{{ $errors->first('harga') }}</strong>--}}
                        {{--                            </span>--}}
                        {{--                        @endif--}}
                    </div>
                </div>
                <div class="form-group">
                    <label for="jenis_menu" class="">Jenis Menu</label>
                    <div class="">
                        <select name="jenis_menu" id="" class="form-control">
                            <option value="Makanan" @if ($data->jenis_menu == 'Makanan') selected @endif>Makanan</option>
                            <option value="Minuman" @if ($data->jenis_menu == 'Minuman') selected @endif>Minuman</option>
                        </select>
                    </div>
                </div>
                <button type="submit" class="btn btn-primary" id="submit">Submit</button>
                <button type="reset" class="btn btn-danger">Reset</button>
                <a href="{{route('menu.index')}}" class="btn btn-light pull-right">Kembali</a>
            </div>
        </div>
    </form>
@endsection

resources/views/menu/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="panel panel-headline">
        <div class="panel-heading" style="padding-bottom: 0px">
            <h3 class="panel-title">Menu</h3>
            <p class="panel-subtitle">Menampilkan berbagai menu pilihan yang disajikan oleh restoran</p>
            @if(Auth::user()->level == 'admin' || Auth::user()->level == 'waiter')
                <a href="{{ route('menu.create') }}" class="btn btn-primary btn-rounded btn-fw" style="margin-top: 10px; margin-bottom: -10px;"><i class="fa fa-plus"></i> Tambah Menu</a>
                <br>
                <br>
            @else
                <a href="" class="btn btn-primary btn-rounded btn-fw disabled" style="margin-top: 10px; margin-bottom: -10px;"><i class="fa fa-plus"></i> Tambah Menu</a>
                <br>
                <br>
            @endif

            @if (Session::has('sukses'))
                <div class="alert alert-success mb-4" role="alert" style="margin-bottom: 0px;">
                    <strong>{{ Session::get('sukses') }}</strong>
                </div>
            @endif
        </div>
        <div class="panel-body">
            <div class="body">
                    <div class="tabel-responsive">
                        <table class="table table-bordered table-hover table-striped" id="dt">
                            <thead>
                            <tr>
                                <th>No</th>
                                <th>Nama</th>
                                <th>Harga</th>
                                <th>Jenis Menu</th>
                                @if(Auth::user()->level == 'admin' || Auth::user()->level == 'waiter')
                                <th>Opsi</th>
                                @endif
                            </tr>
                            </thead>
                            <tbody>
                            @php
                                $i=1
                            @endphp
                            @foreach($data as $m)
                                <tr>
                                    <td>{{ $i++ }}</td>
                                    <td>{{ $m->nama }}</td>
                                    <td>{{ $m->harga }}</td>
                                    <td>{{ $m->jenis_menu}}</td>
                                    @if(Auth::user()->level == 'admin' || Auth::user()->level == 'waiter')
                                    <td>
                                        <div class="column">
                                            <a href="{{route('menu.edit',$m->id)}}" class="btn btn-default fa fa-pencil"></a>
                                            <a class="btn btn-danger fa fa-trash" data-toggle="modal" data-target="#modelId" onclick="prepare({{$m->id}})"></a>                                        </div>
                                    </td>
                                    @endif
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
        </div>
    </div>

        <div class="modal fade" id="modelId" tabindex="-1" role="dialog" aria-labelledby="modelTitleId" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title">Konfirmasi Hapus Menu</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <form action="{{route('menu.destroy', $m->id)}}" method="post">
                        {{ csrf_field() }}
                        {{ method_field('delete') }}
                        <input type="hidden" name="id" id="menuid" readonly>
                        <div class="modal-body">
                            Apakah anda yakin ingin menghapus menu <b><span id="nomer">{{$m->nama}}</span></b>? Aksi ini tidak dapat di-<i>undo</i>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Tidak</button>
                            <input type="submit" value="Hapus" class="btn btn-danger">
                        </div>
                    </form>
                </div>
            </div>
        </div>

@endsection
{{--@section('js')--}}
{{--    <script>--}}
{{--        $(function () {--}}
{{--            $('#dt').DataTable({--}}
{{--                'paging'      : true,--}}
{{--                'lengthChange': true,--}}
{{--                'searching'   : true,--}}
{{--                'ordering'    : true,--}}
{{--                'info'        : true,--}}
{{--                'autoWidth'   : true--}}
{{--            })--}}
{{--        })--}}
{{--    </script>--}}
{{--@endsection--}}